name: dev
include:
  - ./docker/supabase.yml

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    container_name: app
    network_mode: host
    working_dir: /app
    command: >
      npm run dev
    volumes:
      - ./.env:/app/.env
      - ./.env:/app/.dev.vars
      - ./.env.staging:/app/.env.staging
      - ./.env.prod:/app/.env.prod
    mem_limit: "6G"
    cpus: 4
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./src/app
          target: /app
          ignore:
            - /app/node_modules
        - action: rebuild
          path: ./src/app/package.json
